### ISSUE TITLE
When dropping the window to a different editor, the preview turns gray with a "typst-ws process exited with code 255" error

### ISSUE THREAD

**Issue by elteammate** [Enter-tainer/typst-preview-vscode#37] opened 2023-05-27 19:52 UTC
The title. To reproduce, drag a tab with a preview and drop it into anywhere else.

**Comment by elteammate** [comment] 2023-05-27 20:07
Addendum: the error code on Windows is different, (but still -1, clearly). 

Also for some reason, if you drag the tab not by the handle with "Preview" written on it (like, not by an actual tab), but by the top bar of the frame containing that tab, it works just fine.

**Comment by Myriad-Dreamin** [comment] 2023-05-27 20:27
https://github.com/Enter-tainer/typst-preview-vscode/issues/22

**Comment by Enter-tainer** [comment] 2023-06-30 08:00
This issue is workarounded in v0.5.1 because the webview automatically reconnects to the backend.

**Comment by Enter-tainer** [comment] 2023-07-14 13:25
I'll close this issue for now because this no longer happens. Although the root cause still remain.

**Closed by Enter-tainer** 2023-07-14 13:25 UTC
